chore(deps): downgrade podman to v5.4.2
Because of compatibility issues like:
```
Error: ../../../go/pkg/mod/github.com/containers/podman/v5@v5.5.2/libpod/define/config.go:21:21: undefined: types.ErrInvalidName
Error: Process completed with exit code 1.
```