chore(deps): bump the minor group with 3 updates (#188)
* chore(deps): bump the minor group with 3 updates

Bumps the minor group with 3 updates: [github.com/containers/podman/v5](https://github.com/containers/podman), [github.com/containifyci/engine-ci/protos2](https://github.com/containifyci/engine-ci) and [google.golang.org/api](https://github.com/googleapis/google-api-go-client).


Updates `github.com/containers/podman/v5` from 5.4.2 to 5.5.2
- [Release notes](https://github.com/containers/podman/releases)
- [Changelog](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md)
- [Commits](https://github.com/containers/podman/compare/v5.4.2...v5.5.2)

Updates `github.com/containifyci/engine-ci/protos2` from 0.12.2 to 0.12.3
- [Release notes](https://github.com/containifyci/engine-ci/releases)
- [Changelog](https://github.com/containifyci/engine-ci/blob/main/.goreleaser.yaml)
- [Commits](https://github.com/containifyci/engine-ci/compare/protos2/v0.12.2...protos2/v0.12.3)

Updates `google.golang.org/api` from 0.236.0 to 0.242.0
- [Release notes](https://github.com/googleapis/google-api-go-client/releases)
- [Changelog](https://github.com/googleapis/google-api-go-client/blob/main/CHANGES.md)
- [Commits](https://github.com/googleapis/google-api-go-client/compare/v0.236.0...v0.242.0)

---
updated-dependencies:
- dependency-name: github.com/containers/podman/v5
  dependency-version: 5.5.2
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: minor
- dependency-name: github.com/containifyci/engine-ci/protos2
  dependency-version: 0.12.3
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: minor
- dependency-name: google.golang.org/api
  dependency-version: 0.242.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* chore(deps): downgrade podman to v5.4.2

Because of compatibility issues like:
```
Error: ../../../go/pkg/mod/github.com/containers/podman/v5@v5.5.2/libpod/define/config.go:21:21: undefined: types.ErrInvalidName
Error: Process completed with exit code 1.
```

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: fr12k <frank.ittermann@yahoo.de>
Co-authored-by: Frank <126682769+fr12k@users.noreply.github.com>